# Generated by Django 5.2 on 2025-05-06 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('code', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_common', models.CharField(max_length=100)),
                ('name_official', models.CharField(max_length=200)),
                ('native_names', models.JSONField(blank=True, null=True)),
                ('tld', models.JSONField()),
                ('cca2', models.CharField(max_length=2)),
                ('ccn3', models.CharField(max_length=3)),
                ('cca3', models.CharField(max_length=3)),
                ('cioc', models.CharField(blank=True, max_length=3, null=True)),
                ('independent', models.BooleanField(default=False)),
                ('status', models.CharField(max_length=50)),
                ('un_member', models.BooleanField(default=False)),
                ('idd_root', models.CharField(max_length=5)),
                ('idd_suffixes', models.JSONField()),
                ('capital', models.JSONField()),
                ('alt_spellings', models.JSONField()),
                ('region', models.CharField(max_length=50)),
                ('subregion', models.CharField(blank=True, max_length=50, null=True)),
                ('latlng', models.JSONField()),
                ('landlocked', models.BooleanField(default=False)),
                ('area', models.FloatField()),
                ('demonyms', models.JSONField()),
                ('population', models.BigIntegerField()),
                ('gini', models.JSONField(blank=True, null=True)),
                ('fifa', models.CharField(blank=True, max_length=3, null=True)),
                ('car_signs', models.JSONField()),
                ('car_side', models.CharField(max_length=10)),
                ('timezones', models.JSONField()),
                ('flag_emoji', models.CharField(max_length=10)),
                ('flag_png', models.URLField()),
                ('flag_svg', models.URLField()),
                ('coat_of_arms_png', models.URLField(blank=True, null=True)),
                ('coat_of_arms_svg', models.URLField(blank=True, null=True)),
                ('maps_google', models.URLField()),
                ('maps_osm', models.URLField()),
                ('start_of_week', models.CharField(max_length=10)),
                ('capital_info', models.JSONField(blank=True, null=True)),
                ('postal_code_format', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code_regex', models.CharField(blank=True, max_length=200, null=True)),
                ('borders', models.ManyToManyField(blank=True, to='country_info.country')),
                ('continents', models.ManyToManyField(to='country_info.continent')),
                ('currencies', models.ManyToManyField(to='country_info.currency')),
                ('languages', models.ManyToManyField(to='country_info.language')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(max_length=10)),
                ('official', models.CharField(max_length=200)),
                ('common', models.CharField(max_length=200)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='country_info.country')),
            ],
        ),
    ]
