# Generated by Django 5.2 on 2025-05-06 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_info', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='flag_alt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
