# Generated by Django 5.2 on 2025-05-06 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('country_info', '0002_country_flag_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='car_side',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='car_signs',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='cca2',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='cca3',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='ccn3',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='demonyms',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag_emoji',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag_png',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='flag_svg',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='idd_root',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='idd_suffixes',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='maps_google',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='maps_osm',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
