# Generated by Django 5.2 on 2025-05-06 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('country_info', '0003_alter_country_area_alter_country_car_side_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='flag_emoji',
            new_name='flag',
        ),
    ]
